#!/bin/bash
go get github.com/restic/chunker
go get github.com/BurntSushi/toml
# github.com/vmihailenco/msgpack
go build dupver.go snapshot.go pack.go \
   repo.go workdir.go randstring.go util.go
echo "Done building"

install_folder=$HOME/.local/bin
mkdir -p $install_folder
cp dupver $install_folder
echo "Copied to $install_folder"

